name = "vishnuroshan-site"
main = "worker/index.js"
compatibility_date = "2024-11-01"

[assets]
directory = "."
binding = "ASSETS"
not_found_handling = "404-page"

[[r2_buckets]]
binding = "RESUME_BUCKET"
bucket_name = "vishnuroshan-site"
