name = "vishnuroshan-site"
main = "worker/index.js"
compatibility_date = "2024-11-01"

[assets]
directory = "."
binding = "ASSETS"

[[r2_buckets]]
binding = "RESUME_BUCKET"
bucket_name = "vishnuroshan-site"
